version: '3'

services:
  docker.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  docker.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  docker.web2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  docker.mvc2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  docker.web3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  docker.mvc3:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  docker.web4:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  docker.mvc4:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
